variable "node_name" {}
variable "node_name-1" {}
variable "sg_name" {}
variable "ami" {}
variable "instance_type" {}
variable "dev-1-port-1" {}
variable "dev-1-port-2" {}
variable "dev-2-port-1" {}
variable "dev-2-port-2" {}
variable "dev-1-sg-name" {}
variable "dev-2-sg-name" {}
